# defaults:
#   run:
    # working-directory: v2raya-scoop
on:
  workflow_dispatch:
  schedule:
    # run every 8 hours
    - cron: '20 */8 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - uses: Amadevus/pwsh-script@v2.0.1
    - name: Excavate
      run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          New-Item -Type Directory -Path \"D:/scoop/"\
          $env:SCOOP = D:/scoop/
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; iwr get.scoop.sh -outfile 'install.ps1'; .\install.ps1 -RunAsAdmin
          pwsh -c ./bin/checkver.ps1 -Update
          git commit -a -m "update"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
          github_url: https://github.com/v2rayA/v2raya-scoop/
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
